# Generated by Django 3.2 on 2023-03-20 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='poster',
            name='format_type',
            field=models.CharField(choices=[('vertical', 'Vertical'), ('horizontal', 'Horizontal')], max_length=15),
        ),
        migrations.AlterField(
            model_name='poster',
            name='image_path',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='poster',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
