# Generated by Django 3.2 on 2023-03-21 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20230320_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
