# Generated by Django 3.2 on 2023-03-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_poster_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image_path',
            field=models.ImageField(upload_to='posters/'),
        ),
    ]
